language: android
android:
  components:
    - tools     
    - platform-tools
    - tools 
    - build-tools-26.0.1
    - android-26
    - extra-android-support
    - extra-android-m2repository
    
   
notifications:
  email: false
  
before_install:
 - chmod +x gradlew 
