language: android
script: ./gradlew build assembleRelease
android:
  components:
  - build-tools-20.0.0
  - android-19
notifications:
  email: false
 
deploy:
  provider: releases  
  file: app/build/outputs/apk/app-release.apk
  skip-cleanup: true 
  
  on:
    branch: testingDeploy
    repo: kylemathias/SDCardBuilder
    tags: true    
    
  api_key:
    secure: DnJ2fHeGuY74PGRDp1q58dzW4fABxEhm6VpcTxiMxPOPlrhm7KdhuKXYljMr5vDcXqzK44jWQEJlCWZMYKpdGopwqs3KgpCOiD0pUyas1LXewr1h8SQaLCVUKVwYWRd/r7/i0VUQV8N+P0aokI95k/Xw2xfrkWjYdYIYg5+eBMCb7ykUY1Qd8KaaKJsmCNZ/7fqRw7sFk8HfAAzYF1mC1YUSgtlB6Ry1aAkTGeUG7DyYiYKG/2OxC4yWwwIi+ZGZ2gxqh2Dwy2eGRck/RblFFlHkvrvecn0p8ayyWziKRVAy0MZkWFET6QCSbpPyejHBE4apUqx2jhY/tvnFoHsW7qiqynZOS4i4nH8Km0ikyIt3DV3G0clGTnXXvBQZ002VInKhxlYCtiYVgYSrLf7WWsr+aI85BLDLqVB+7wg2TtqAqX89fw0vnX5zXB0qCh3BwVmPDuBY6+9pOOEjE2H5ZOb3qKA9S+RNQGdmtnLcHjIaa7SEX+RmoLWsPbHhoViE2F6hXWFRIqsnV+YtDU4L0nGTI+6fc3+H27veUQPmJsAEFYtn1/tnAgujS+3ubd+j8LgwaOp/1hKrBal8Cxono+rIU+7fEX1Q2gnMz6UzO7MJSESuCIM8P08idb9QyRcX0NZq1T9jdejwXStMSmJvSGwA3GaQnakeSTlmPFLZrbo=  
