language: android
android:
  components:
    - tools 
    - tools 
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-android-support
    - extra-android-m2repository
    
script:
    -./gradlew build
    - ./gradlew build connectedCheck
    - chmod +x ./gradlew
   
notifications:
  email: false
  
before_install:
 - chmod +x gradlew